services:
  - type: web
    name: nba-salary-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
    branch: main
    plan: free
